<?php
/**
 * @file
 * Code for the proc message module.
 */



/**
 * Implements hook_cipher_postsave_success_encryption_message_alter().
 */
function proc_message_cipher_postsave_success_encryption_message_alter(&$success_encryption_message, $context) {
  // Get source field of cipher:
  $action_url_parameters = drupal_parse_url($context['unalterable_encryption_source_form']['#action'])['query'];
  if (isset($action_url_parameters['proc_refield_field_id'])) {
    // If cipher comes from private message:
    if (
      // Private message:
      $action_url_parameters['proc_refield_field_id'] == 'field_proc_cipher_reference' && $action_url_parameters['proc_privatemessage']
    ){
      $success_encryption_message = '';
    }
  }
}
