<?php

/**
 * @file
 * Provide pgp encryption for files.
 */

include_once 'inc/proc.functions.inc';

/**
 * Implements hook_permission().
 */
function proc_permission() {
  return array(
    'register protected content keys' => array(
      'title' => t('Register protected content keys'),
      'description' => t('Allow user to access Protected Content Keys registration page.'),
    ),
    'new protected file' => array(
      'title' => t('Create new protected file'),
      'description' => t('Allow user to access Create New Protected File page.'),
    ),
    'create cipher' => array(
      'title' => t('Create new cipher'),
      'description' => t('Allow user to create new cipher entity.'),
    ),
    'view cipher' => array(
      'title' => t('View cipher'),
      'description' => t('Allow user to view cipher entity.'),
    ),

  );
}

/**
 * Implements hook_help().
 */
function proc_help($path) {
  switch ($path) {
    case "admin/help#proc":
      return '<p>' . t('Protected Content (proc) provides end-to-end/client side encryption for content.') . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function proc_menu() {

  $items['proc/keyring/add'] = array(
    'title' => 'Add Protected Content Key',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_proc_generate_keys'),
    'access arguments' => array('register protected content keys'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/proc.forms.inc',
  );
  $items['proc/add/%'] = array(
    'title' => 'Add file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_proc_encrypt_file', 2),
    'access arguments' => array('new protected file'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/proc.forms.inc',
  );
  $items['proc/%'] = array(
    'title' => 'View Protected Content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_proc_decrypt_to_file', 1),
    'access callback' => '_proc_recipient',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'inc/proc.forms.inc',
  );
  return $items;
}

/**
 * Implements hook_views_api().
 */
function proc_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'proc') . '/inc',
  );
}

/**
 * Implements hook_libraries_info().
 */
function proc_libraries_info() {
  $libs = array();

  $crypto_info = _proc_get_cryptolib_settings();

  $libs[$crypto_info['folder']] = array(
    'name' => $crypto_info['versionstring'],
    'vendor url' => $crypto_info['vendor'],
    'download url' => $crypto_info['url'],
    'version arguments' => array(
      'file' => $crypto_info['file'],
      'pattern' => '/v(([0-9]\.?)+)/',
      'lines' => 1,
      'cols' => 24,
    ),
    'files' => array(
      'js' => array($crypto_info['file']),
    ),
  );

  return $libs;
}

/**
 * Implements hook_entity_info().
 */
function proc_entity_info() {
  $info = array(
    'proc' => array(
      'label' => t('Protected Content'),
      'entity class' => 'Proc',
      'base table' => 'proc',
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'entity keys' => array(
        'id' => 'pid',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
      'bundles' => array(
        'proc_keyring' => array(
          'label' => t('Keyring'),
        ),
        'proc_ciphertxt' => array(
          'label' => t('Ciphertext'),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Default'),
          'custom settings' => FALSE,
        ),
      ),
      'module' => 'proc',
      'access callback' => 'proc_access',
      'controller class' => 'EntityAPIController',
      'metadata controller class' => '',
      'fieldable' => TRUE,
      'views controller class' => 'EntityDefaultViewsController',
    ),
  );
  return $info;
}

/**
 * Implements hook_entity_property_info().
 *
 * It is not necessary to describe metadata for fields created with
 * field_create_instance function. Metadata for these fields is
 * created automatically.
 */
function proc_entity_property_info() {
  $info = array();
  $properties = &$info['proc']['properties'];

  $properties['pid'] = array(
    'type' => 'integer',
    'schema field' => 'pid',
    'label' => t('Proc Armored entity ID'),
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['type'] = array(
    'type' => 'text',
    'schema field' => 'type',
    'required' => TRUE,
    'label' => t('Proc Armored entity type (bundle)'),
    'setter callback' => 'entity_property_verbatim_set',
  );
  // @TODO: deprecate uid property in favor of user referance field.
  $properties['uid'] = array(
    'type' => 'user',
    'schema field' => 'uid',
    'required' => TRUE,
    'label' => t('Proc Armored author'),
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['title'] = array(
    'type'  => 'text',
    'schema field' => 'title',
    'required' => TRUE,
    'label' => t('Protected content title'),
    'description' => t('Friendly identifier for armored data'),
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['status'] = array(
    'type' => 'boolean',
    'schema field' => 'status',
    'label' => t('Proc Armored entity status'),
    'setter callback' => 'entity_property_verbatim_set',
  );
  $properties['created'] = array(
    'type' => 'date',
    'schema field' => 'created',
    'required' => TRUE,
    'label' => t('Proc Armored created timestamp'),
    'setter callback' => 'entity_property_verbatim_set',
  );

  return $info;
}

/**
 * Proc class.
 */
class Proc extends Entity {
  protected function defaultURI() {
    if (($this->type == 'proc_ciphertxt') && (_proc_recipient($this->identifier()))) {
      return array('path' => 'proc/' . $this->identifier());
    }
    return FALSE;
  }
  protected function defaultLabel() {
    return $this->title;
  }
}

/**
 * Access callback for Proc.
 */
function proc_access($op, $task, $account = NULL, $entity_type = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
    case 'create':
      return user_access('create cipher', $account);
    case 'view':
      return user_access('view cipher', $account);
  }
}
