# Schema for the configuration files of the Protected Content module.
proc.settings:
  type: config_object
  label: 'Protected Content settings'
  mapping:
    example:
      type: string
      label: 'Example'
