proc.settings:
  type: mapping
  label: Settings
  mapping:
    proc_update_7003_memory_limit:
      type: string
    proc_storage_global_stream_wrapper:
      type: string
    proc_storage_enabled:
      type: integer
    proc_storage_file_name_prefix:
      type: string
    proc_skip_size_mismatch:
      type: boolean
