# Schema for the configuration files of the Protected Content module.
proc.settings:
  type: config_object
  label: 'Protected Content settings'
  mapping:
    example:
      type: string
      label: 'Example'


# Default value.
field.value.field_proc_example:
  type: mapping
  label: Default value
  mapping:
    value_1:
      type: string
      label: Value 1
    value_2:
      type: string
      label: Value 2
    value_3:
      type: string
      label: Value 3

proc.proc_type.*:
  type: config_entity
  label: Proc Type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

field.field_settings.proc_proc_entity_reference_field:
  type: mapping
  label: Proc Entity Reference Field field settings
  mapping:
    bar:
      type: string
      label: Bar

field.value.proc_proc_entity_reference_field:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.widget.settings.proc_proc_entity_reference_field_widget:
  type: mapping
  label: Proc Entity Reference Field Widget widget settings
  mapping:
    foo:
      type: string
      label: Foo
