# Schema for the configuration files of the Protected Content module.
proc.settings:
  type: config_object
  label: 'Protected Content settings'
  mapping:
    example:
      type: string
      label: 'Example'

field.field_settings.proc_entity_reference_field:
  type: mapping
  label: Proc Entity Reference Field settings
  mapping:
    bar:
      type: string
      label: Bar

field.value.proc_entity_reference_field:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

field.widget.settings.proc_entity_reference_widget:
  type: mapping
  label: Proc Entity Reference Field Widget widget settings
  mapping:
    foo:
      type: string
      label: Foo
    size:
      type: integer
      label: 'Size'